export const AUTH_TYPE = {
    REGISTER_USER: 'REGISTER_USER',
    LOGIN_USER: 'LOGIN_USER'
}

export const PRODUCT_TYPE = {
    GET_ALL_PRODUCT: 'GET_ALL_PRODUCT',
    GET_DETAIL_PRODUCT: 'GET_DETAIL_PRODUCT'
}

export const MARKET_TYPE = {
    GET_ALL_MARKET: 'GET_ALL_MARKET',
    GET_DETAIL_MARKET: 'GET_DETAIL_MARKET'
}